# nothing here
CONFIG_ADC=y
CONFIG_ADC_NRFX_SAADC=y
CONFIG_PWM=y
CONFIG_GPIO=y

# EasyDMA
CONFIG_NRFX_SAADC=y
CONFIG_NRFX_TIMER1=y
CONFIG_NRFX_GPPI=y
CONFIG_LOG_BACKEND_SWO=n

# LOG
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# system
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_MAIN_STACK_SIZE=2048